_name_: hg38
bed_file: null
fasta_file: null
dataset_name: hg38
tokenizer_name: null
cache_dir: null
max_length: 1024
add_eos: True
batch_size: 8  # per GPU
batch_size_eval: 16 #${eval:${.batch_size} * 2}
num_workers: 4  # For preprocessing only
shuffle: True
__train_len: 34021
__l_max: ${.max_length}